### ISSUE TITLE
モビグラスのミッションを開くと、クライアントが落ちる

### ISSUE THREAD

**Issue by Luke-514** [stdblue/StarCitizenJapaneseResources#1]
ブランチ
master

grobal.ini バージョン
v3.20.0b

Commitバージョン
c5ce0f4

再現手順
1. モビグラスを開く
2. ミッションを開く

**Comment by stdblue** [comment]
現状、機械翻訳において SC の変数が正常に翻訳されていません。
本来であればこれらの変数、 ~missin(Item) など、は翻訳しない対象として扱うべきですが、DeepL は文脈を解釈するため、無理矢理翻訳をし、SC クライアントに対して致命的な障害を発生させます。

暫定対応として、変数の含まれたメッセージを翻訳せず、原文をそのまま出力します。
